// Centralized re-exports of every Lucide icon used in the app, so we keep
// imports tidy and prevent duplicate decorative icons creeping in.

export {
  AlertCircle,
  ArrowLeft,
  Check,
  GitBranch,
  GitCommit,
  Minus,
  Search,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeftRight,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Code2,
  CornerDownLeft,
  Folder,
  FolderOpen,
  File,
  FileCode2,
  FileX,
  GitCompare,
  History,
  Inbox,
  Keyboard,
  Loader2,
  Menu,
  Mic,
  MicOff,
  Plus,
  RefreshCw,
  RotateCcw,
  Skull,
  SquareTerminal,
  Trash2,
  X,
} from "lucide-react";
